[package]
name = "alphatest"
version = "0.1.0"
edition = "2021"

[dependencies]
core = {path = "../../core"}
window = {path = "../../window"}
app = {path = "../../app"}
env_logger = "0.11"
geometry = {path="../../geometry"}