[package]
name = "gstudy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.25" }
wgpu = "0.8"
futures = "0.3"
egui = "0.12"
env_logger = "0.8"
log = "0.4"
lazy_static = "1.4"

[build-dependencies]
shaderc = "0.7"