[workspace]
members = ["./core", "./app", "./tshader", "./tshader-builder"
    , "./gltfloader", "./window", "./geometry", "./phong-render"
    , "./egui-render", "examples/triangle", "examples/egui", "examples/gltf-viewer"
    , "examples/empty", "examples/cube"]
resolver = "2"