[workspace]
members = ["./core", "./app", "./tshader", "./tshader-builder"
    , "./gltfloader", "./window", "./geometry"
    , "./egui-render", "examples/triangle", "examples/egui", "examples/gltf-viewer"]
resolver = "2"