[pass-0]
name = "basic-forward"
source = "forward.wgsl"
binding = ["pre_camera"]
camera = "d3"

[pass-0.variants.unit]
t = "TEXTURE_COLOR"
n = "NORMAL_TEX"
p = "HEIGHT_TEX"
e = "EMISSION_TEX"
c = "VERTEX_COLOR"
a = "ALPHA_TEST"

[pass-0.variants]
excludes = []
exclusives = ["tc"]
