[[pass]]
index = 0
name = "basic-forward"
source = "forward.wgsl"
binding = ["pre_camera"]
camera = "D3"
shaders = ["vs", "fs"]

[pass.variants]
excludes = []
exclusives = []
unit = ["TEXTURE", "VERTEX_COLOR", "ALPHA_TEST", "CONST_COLOR"]


[tech]
author="kadds"
name="basic_forward"

