[[pass]]
index = 0
name = "phong-forward"
source = "forward_base.wgsl"
binding = ["pre_camera"]
camera = "D3"
shaders = ["vs", "fs"]

[pass.variants]
excludes = []
exclusives = []
unit = ["DIFFUSE_CONSTANT", "DIFFUSE_VERTEX", "DIFFUSE_TEXTURE", "DIRECT_LIGHT", 
"ALPHA_TEST", "NORMAL_VERTEX", "NORMAL_TEXTURE", "SPECULAR_CONSTANT", "SPECULAR_VERTEX", 
"SPECULAR_TEXTURE"]

[[pass]]
index = 1
name = "phong-forward-add"
source = "forward_add.wgsl"
binding = ["pre_camera"]
camera = "D3"
shaders = ["vs", "fs"]
[pass.variants]
excludes = []
exclusives = []
unit = ["DIFFUSE_CONSTANT", "DIFFUSE_VERTEX", "DIFFUSE_TEXTURE", "POINT_LIGHT",  "SPOT_LIGHT",
"ALPHA_TEST", "NORMAL_VERTEX", "NORMAL_TEXTURE", "SPECULAR_CONSTANT", "SPECULAR_VERTEX", 
"SPECULAR_TEXTURE"]

[tech]
author="kadds"
name="phong_forward"
