[[pass]]
index = 0
name = "phong-forward"
source = "forward_base.wgsl"
binding = ["pre_camera"]
camera = "D3"
shaders = ["vs", "fs"]

[pass.variants]
excludes = []
exclusives = ["TEXTURE_COLOR|VERTEX_COLOR"]
unit = ["DIFFUSE_CONSTANT", "DIFFUSE_VERTEX", "DIFFUSE_TEXTURE", "DIRECT_LIGHT", 
"ALPHA_TEST", "NORMAL_VERTEX", "NORMAL_TEXTURE", "SPECULAR_CONSTANT", "SPECULAR_VERTEX", 
"SPECULAR_TEXTURE", "SHADOW_MAP"]

[[pass]]
index = 1
name = "phong-forward-add"
source = "forward_add.wgsl"
binding = ["pre_camera"]
camera = "D3"
shaders = ["vs", "fs"]
variants = { excludes = [], exclusives = ["TEXTURE_COLOR|VERTEX_COLOR"], unit = ["TEXTURE_COLOR", "NORMAL_TEX", "HEIGHT_TEX", "EMISSION_TEX", "VERTEX_COLOR", "ALPHA_TEST"]}


[tech]
author="kadds"
name="phong_forward"
